### ISSUE TITLE
Data location is ambiguous

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_Tutorial#122]
It is unclear where the data has to go. I'm following the tutorial `Using your own machine`

The wget script downloads the data to `$HOME/default_inputpath/`:

```bash
wget --no-clobber --input-file \
  https://github.com/ESMValGroup/ESMValTool_Tutorial/raw/master/data/dataset.urls \
  --directory-prefix $HOME/default_inputpath/
```

But in the setup, we are asked to use `~/esmvaltool_tutorial/data`:

```yaml
  rootpath:
  ...
    CMIP5: [~/cmip5_inputpath1, ~/cmip5_inputpath2, ~/esmvaltool_tutorial/data]
```

However, this results in `esmvalcore._recipe_checks.RecipeError: Missing data`.
