### ISSUE TITLE
Improve episodes 4 & 5

### ISSUE THREAD

**Issue by Peter9192** [ESMValGroup/ESMValTool_Tutorial#142]
Problem:
We tried to teach the lesson as is. Currently, episode 5 (working with the preprocessor) is very similar to episode 4 (running your first recipe). Both of the lessons have exercises to edit/play with the recipe and then run the tool. However, there is no clear storyline in the kind of edits we're doing in either of the episodes. Moreover, what's currently missing in the tutorial is a showcase of 'how easy it is to reproduce results from others/papers'. That is something that really characterizes ESMValTool.

Therefore, I propose the following changes:

## Episode 4: Reproducing results from previous studies by running existing recipes

- Use `esmvaltool recipes list` to show the list of all available recipes
- Use `esmvaltool recipes get` to copy an existing recipe to your computer
- Inspect the recipe (not very detailed, but just to get a general idea of what it does)
- Checkout the documentation and example output on readthedocs
- Run the recipe (a suitable recipe should be chosen such that the data demand is not too high).
- Be amazed 
- Explain that this works best if you're near an ESGF node with a shitload of data available.
- Maybe we could use `--max_years` or `--max_datasets` flags to limit the amount of data needed to run the recipe

## Episode 5: Build up your own recipe 'from scratch'
Adding 1 single step at a time (each step is an exercise). The exercises build up in complexity, and we can stop whenever we reach the time or brain limit.

Start with:

```Yaml
documentation:
  description: My first recipe
  authors:
    - dummy_name
  maintainer:
    - dummy_name
  references:
    - dummy_bibtex_key
  projects:
    - dummy_project

datasets:
# This is where we specify the datasets that the recipe should use

preprocessors:
# This is where we will specify the preprocessor steps

diagnostics:
# This is where we will specify the diagnostics we want to create
  dummy_diagnostic_1:
    description: my first diagnostic
    variables:
      interesting_variable_1:
        short_name: dummy
    scripts: null
```

Then we can expand on it using the following steps/exercises (run esmvaltool after each step):

##### Analysis of global mean temperature rise
1. Add a single dataset and a single variable (tas). This is just to show that ESMValTool can locate your data.
2. Add preprocessor: global mean. Inspect the output in the preproc directory. Look at the dimensions with ncdump or so.
3. Add diagnostic script: plot timeseries. This script should already have been prepared, but can be viewed. 
5. Add anomalies preprocessor (so now we have 2 preprocessor steps). 
6. Add another dataset. So now we can compare.
7. Add the multimodel statistics preprocessor, to see the single overall temperature rise that the models agree on.

##### Temperature rise at different locations
8. Change the preprocessor to not take the global mean, but instead select a point
9. Split the preprocessor in 2: use a different location for both
10. Use yaml anchors to condense the recipe format a bit

##### Impact of area selection method
11. Change one of the preprocessors, to use extract-region with a box around the central point, and then use area-statistics to get the region mean

##### Special topics  
12. Ensemble members / ensemble statistics
13. Using yaml anchors
14. Variable groups
...
