### ISSUE TITLE
ValueError in Lesson 10 CMORization: adding new datasets to ESMValTool 

### ISSUE THREAD

**Issue by gulcing** [ESMValGroup/ESMValTool_Tutorial#299]
As explained in Lesson 10 CMORization: adding new datasets to ESMValTool part of “ Run the existing CMORizer script”, I couldn’t run the existing CMORizer script.
  
> https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/4c08c162e3c7ac9e8107a1d4c8b166082e618426/_episodes/09-cmorization.md?plain=1#L123

And got this error:

**raise ValueError(msg) ValueError: No format specification could be found for the given buffer. Perhaps a plugin is missing or has not been loaded. File element cache: {'UriProtocol()': 'file', 'LeadingLine()': "b'\x89HDF\n'", 'MagicNumber(4, None)': '2303214662', 'MagicNumber(8, None)': '9892231649127172610', 'DataSourceObjectProtocol()': 'GPP.ANN.CRUNCEPv6.monthly.2000.nc', 'FileExtension()': '.nc', 'MagicNumber(100, None)': "b'\x89HDF\n\x1a\n\x02\x08\x08\x00\x00\x00\x00\x00\..."}**

This is config-user.yml file:

```

# Destination directory where all output will be written
# Includes log files and performance stats.
output_dir: ~/esmvaltool_output

# Auxiliary data directory
# Used by some recipes to look for additional datasets.
auxiliary_data_dir: ~/auxiliary_data

# Automatic data download from ESGF --- [never]/when_missing/always
# Use automatic download of missing CMIP3, CMIP5, CMIP6, CORDEX, and obs4MIPs
# data from ESGF. ``never`` disables this feature, which is useful if you are
# working on a computer without an internet connection, or if you have limited
# disk space. ``when_missing`` enables the automatic download for files that
# are not available locally. ``always`` will always check ESGF for the latest
# version of a file, and will only use local files if they correspond to that
# latest version.
search_esgf: never

# Directory for storing downloaded climate data
# Make sure to use a directory where you can store multiple GBs of data. Your
# home directory on a HPC is usually not suited for this purpose, so please
# change the default value in this case!
download_dir: ~/climate_data

# Run at most this many tasks in parallel --- [null]/1/2/3/4/...
# Set to ``null`` to use the number of available CPUs. If you run out of
# memory, try setting max_parallel_tasks to ``1`` and check the amount of
# memory you need for that by inspecting the file ``run/resource_usage.txt`` in
# the output directory. Using the number there you can increase the number of
# parallel tasks again to a reasonable number for the amount of memory
# available in your system.
max_parallel_tasks: null

# Log level of the console --- debug/[info]/warning/error
# For much more information printed to screen set log_level to ``debug``.
log_level: info

# Exit on warning --- true/[false]
# # Only used in NCL diagnostic scripts.
exit_on_warning: false

# Plot file format --- [png]/pdf/ps/eps/epsi
output_file_type: png

# Remove the ``preproc`` directory if the run was successful --- [true]/false
# By default this option is set to ``true``, so all preprocessor output files
# will be removed after a successful run. Set to ``false`` if you need those
# files.
remove_preproc_dir: true

# Use netCDF compression --- true/[false]
compress_netcdf: false

# Save intermediary cubes in the preprocessor --- true/[false]
# Setting this to ``true`` will save the output cube from each preprocessing
# step. These files are numbered according to the preprocessing order.
save_intermediary_cubes: false

# Path to custom ``config-developer.yml`` file
# This can be used to customise project configurations. See
# ``config-developer.yml`` for an example. Set to ``null`` to use the default.
config_developer_file: null

# Use a profiling tool for the diagnostic run --- [false]/true
# A profiler tells you which functions in your code take most time to run.
# Only available for Python diagnostics.
profile_diagnostic: false

# Rootpaths to the data from different projects
# This default setting will work if files have been downloaded by ESMValTool
# via ``search_esgf``. Lists are also possible. For site-specific entries and
# more examples, see below. Comment out these when using a site-specific path.
rootpath:
  default: ~/climate_data
  RAWOBS: /home/b/b382650/ESMValTool/data/RAWOBS
  
# Directory structure for input data --- [default]/ESGF/BADC/DKRZ/ETHZ/etc.
# This default setting will work if files have been downloaded by ESMValTool
# via ``search_esgf``. See ``config-developer.yml`` for definitions.  Comment
# out/replace as per needed.
drs:
  CMIP3: DKRZ
  CMIP5: DKRZ
  CMIP6: DKRZ
```

**Comment by gulcing** [comment]
I checked the config file and changed the rootpath depending on the folder as follows: 

```
# Rootpaths to the data from different projects
# This default setting will work if files have been downloaded by ESMValTool
# via ``search_esgf``. Lists are also possible. For site-specific entries and
# more examples, see below. Comment out these when using a site-specific path.
rootpath:
  default: ~/climate_data
  RAWOBS: /work/bd1083/b382650/data/RAWOBS
  OBS6: /work/bd1083/b382650/data/OBS6
```
